### PR TITLE
Fix principal exclusion in case of comma in the name

### LINKED ISSUE #49: Principal exclusion feature doesn't work if the principal contains a comma (such as Distinguished Name)
The plugin's configuration supports `client.quota.callback.static.excluded.principal.name.list` which allows the user to pass a list of principals that should not be subject to the quota.  The entries in the list are comma separated.  This scheme does not allow for the possibility that the principal name may include a comma, as is the case with DNs.

For instance, one might want to exclude mirrormaker from the quota.

`client.quota.callback.static.excluded.principal.name.list=CN=my-cluster-cruise-control,O=io.strimzi`

This will not have the intended effect as `CN=my-cluster-cruise-control` and `O=io.strimzi` will be interpreted as referring to separate principals.  There's no way to escape the comma (the plugin leans on  [`ConfigDef#parseType`](https://github.com/apache/kafka/blob/3ad648243c72adbd7ba6e52cbaff143b551884b1/clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java#L755) to marshal a string into a list, but there is no escape mechanism).

### PR DESCRIPTION
**Pull request by im-konge**
This PR fixes issues with the principal exclusion in case that the comma (`,`) is specified in the name -> for example in case of Distinguished Name.
It changes the separator to semicolon, so from now on it should be "semicolon-separated" list, as it is in case of authorization in Kafka (when configuring `super.users`).

To follow the `super.users` completely, this PR adds requirement to prefix the principals with `User:` prefix. In case that the principal is missing the prefix, an exception is thrown.

Fixes #49

### CODE REVIEW

**Comment by scholzj** [comment]
I think this is a bit pre-mature. We should first finish the discussion about how to address #49. I do not think we had any agreement on the issue.

File: src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java [hunk 1]
```diff
@@ -76,7 +78,7 @@ public StaticQuotaConfig(Map<String, ?> props, boolean doLog) {
                         .define(PRODUCE_QUOTA_PROP, DOUBLE, Double.MAX_VALUE, HIGH, "Produce bandwidth rate quota (in bytes)")
                         .define(FETCH_QUOTA_PROP, DOUBLE, Double.MAX_VALUE, HIGH, "Consume bandwidth rate quota (in bytes)")
                         .define(REQUEST_QUOTA_PROP, DOUBLE, Double.MAX_VALUE, HIGH, "Request processing time quota (in seconds)")
-                        .define(EXCLUDED_PRINCIPAL_NAME_LIST_PROP, LIST, List.of(), MEDIUM, "List of principals that are excluded from the quota")
+                        .define(EXCLUDED_PRINCIPAL_NAME_LIST_PROP, STRING, "", MEDIUM, "List of principals that are excluded from the quota")
```
Comment (k-wall) [inline src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java:81]: Why empty string for the default value?  Why not null?

**Comment by im-konge** [comment]
> I think this is a bit pre-mature. We should first finish the discussion about how to address https://github.com/strimzi/kafka-quotas-plugin/issues/49. I do not think we had any agreement on the issue.

Ah okay, sorry. I thought that we are going this way. Anyway, back to the issue :)

File: src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java (hunk 1 above)
Comment (im-konge) [reply src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java:81]: I wanted to have default to empty String, as the split can cause NPE in case of null, or?

File: src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java [hunk 2]
```diff
@@ -123,7 +125,7 @@ int getStorageCheckInterval() {
     }
 
     List<String> getExcludedPrincipalNameList() {
-        return getList(EXCLUDED_PRINCIPAL_NAME_LIST_PROP);
+        return Arrays.stream(getString(EXCLUDED_PRINCIPAL_NAME_LIST_PROP).split(";")).collect(Collectors.toList());
```
Comment (k-wall) [inline src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java:128]: needs to guard the null case.

File: src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java (hunk 1 above)
Comment (k-wall) [reply src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java:81]: yes, your way functions, but it is weird.  The effect will be the excludedPrinicipal list ends up a singleton list with an empty string as a member.  Better to handle the null explicitly and have that produce an empty list.

Comment (im-konge) [reply src/main/java/io/strimzi/kafka/quotas/StaticQuotaConfig.java:81]: Yeah, makes sense. Good catch :) thanks

File: CHANGELOG.md [hunk 3]
```diff
@@ -2,9 +2,13 @@
 
 * Allow specifying check-interval higher than 0 together with no limit configuration
 * Set default check-interval to 60s
+
+## 0.3.1
```
Comment (scholzj) [inline CHANGELOG.md:6]: I think both changes should go into 0.3.1 and you need anyway both for the operator PR.

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,9 +2,13 @@
...
 * Change excluded principal definition to be semicolon-separated list
 
 ### Changes, deprecations and removals
 
-* **Important:** From 0.4.0 the excluded principals are configured as semicolon-separated list. In previous versions, the principals were
-configured using comma-separated list.
\ No newline at end of file
+* **Important:** From 0.3.1 the excluded principals are configured as semicolon-separated list. In previous versions, the principals were
+configured using comma-separated list.
+This fixes the issue with Distinguish Names, which were wrongly separated by the comma.
```
Comment (scholzj) [inline CHANGELOG.md:14]:
```suggestion
* **Important:** 0.3.1 fixes a bug from 0.3.0 release where the excluded principals were separated by a comma instead of a semi-colon.
  If you use the `<xxx>` option, please update your configuration and use `;` as separators.
```

File: CHANGELOG.md
Comment (scholzj) [inline CHANGELOG.md:1]: I don't think I would add change log for this. Keep it for the release notes.

File: README.md [hunk 5]
```diff
@@ -46,23 +46,23 @@ client.quota.callback.static.storage.per.volume.limit.min.available.bytes=536870
 client.quota.callback.static.storage.check-interval=5
 
 # Optional list of principals not to be subjected to the quota
-client.quota.callback.static.excluded.principal.name.list=principal1,principal2
+client.quota.callback.static.excluded.principal.name.list=principal1;principal2
```
Comment (scholzj) [inline README.md:49]: As we compere this with the `super.users` option from Kafka -> should this also expect the `User:` prefix to be used?

Comment (im-konge) [reply README.md:49]: From my understanding, we are here just checking that the name of the `KafkaPrincipal` inside is in the list of excluded principals.
Kafka (at least what I see here https://github.com/apache/kafka/blob/53ff1a5a589eb0e30a302724fcf5d0c72c823682/clients/src/main/java/org/apache/kafka/common/utils/SecurityUtils.java#L63) splits the whole `User: xxx` by `:` and the `User` part uses as a type of the `KafkaPrincipal` and everything after `:` as name.

Comment (im-konge) [reply README.md:49]: So I think that it should not be `User:principal1;User:principal2`, as only the name part is used anyway.

File: CHANGELOG.md
Comment (im-konge) [reply CHANGELOG.md:1]: So you mean that I should remove the CHANGELOG and keep the notes to the release notes of the 0.3.1, where all the changes should be present, right? (just want to be sure that I understand it correctly)

File: README.md (hunk 5 above)
Comment (scholzj) [reply README.md:49]: And how do you know that type of principal should it apply to?

File: CHANGELOG.md
Comment (scholzj) [reply CHANGELOG.md:1]: yes.

Comment (im-konge) [reply CHANGELOG.md:1]: ok, thanks :)

File: README.md (hunk 5 above)
Comment (im-konge) [reply README.md:49]: So I think that originally the plugin assumed that the principals will be of type `User`.
But I can add parsing similar as Kafka has.
And in case that there will be nothing like `User:` or whatever, it will default to `User` in the check.

Comment (im-konge) [reply README.md:49]: Yeah, maybe it's something that we should discuss more.
Based on https://kafka.apache.org/37/javadoc/org/apache/kafka/common/security/auth/KafkaPrincipal.html , the `User` as a type will be used always for the simple authorizer. However based on the authz, there can be something else. So maybe to prevent issues in the future, it would make sense to follow the `super.users` completely.

Comment (k-wall) [reply README.md:49]: > Yeah, maybe it's something that we should discuss more.
Based on https://kafka.apache.org/37/javadoc/org/apache/kafka/common/security/auth/KafkaPrincipal.html , the User as a type will be used always for the simple authorizer. 

Right.   I did wonder whether it would be possible to allow exclusions to be specified for other principal types  (`Group:` for instance), I came to the conclusion that the `quotaMetricTags` API doesn't allow that possibility. `KafkaPrincipal` is just the user.

I don't think prefixing the principals in the list with User: gets us much.    If we did go that route, we'd have to fail if ever configured with a principal prefix apart from `User:`.

File: CHANGELOG.md (hunk 4 above)
Comment (scholzj) [reply CHANGELOG.md:14]: 0.2.0 does not seem to list any excluded principals option. I think that is new in 0.3.0, or?

Comment (robobario) [reply CHANGELOG.md:14]: Yes, this is new in 0.3.0. 

We had this configuration option in a downstream fork (based on 0.2.0) for a long time but it didn't make it back upstream until now.

**Review by robobario — APPROVED** [review]
LGTM. thanks @im-konge

File: README.md (hunk 5 above)
Comment (im-konge) [reply README.md:49]: Based on the above findings, I guess we are keeping it as it is?

File: CHANGELOG.md (hunk 4 above)
Comment (k-wall) [reply CHANGELOG.md:14]: ah. I see.

File: README.md (hunk 5 above)
Comment (ppatierno) [reply README.md:49]: So ... I see that the quota API seems to use always `User` type as stated above. At the same time, we could be prepared for future changes if a different type could be used. What about having the `User:principal1;User:principal2` as the official format but defaulting to `User` when it's absent so allowing even the current `principal1:principal2` ? Maybe it's something suggested by @im-konge previously.

Comment (k-wall) [reply README.md:49]: I think the Kafka API is unlikely to change any time soon, so I don't think words like "at the moment" really help.  If you want, add an example to the table in the README illustrating thus illustrating that the principal is unprefixed.

Comment (im-konge) [reply README.md:49]: Discussed on the community call on May 2nd: We will follow the pattern of `super.users` completely, thus prefixing the principal with `User:` prefix.

I will change the PR accordingly.

File: CHANGELOG.md
Comment (im-konge) [reply CHANGELOG.md:1]: Added the suggestions and moved it outside of the PR. Thanks :)

**Comment by im-konge** [comment]
@scholzj @k-wall @robobario @ppatierno I changed the PR after the discussion around `User:` prefix, could you please check it again? Thanks!

File: src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java [hunk 6]
```diff
@@ -198,7 +198,7 @@ void excludedPrincipal() {
         KafkaPrincipal foo = new KafkaPrincipal(KafkaPrincipal.USER_TYPE, "foo");
 
         target.configure(Map.of(
-                StaticQuotaConfig.EXCLUDED_PRINCIPAL_NAME_LIST_PROP, "foo,bar",
+                StaticQuotaConfig.EXCLUDED_PRINCIPAL_NAME_LIST_PROP, "User:foo;User:bar;User:CN=my-cluster,O=io.strimzi;arnost",
```
Comment (scholzj) [inline src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java:201]: Should there be `User:`?

```suggestion
                StaticQuotaConfig.EXCLUDED_PRINCIPAL_NAME_LIST_PROP, "User:foo;User:bar;User:CN=my-cluster,O=io.strimzi;User:arnost",
```

Comment (im-konge) [reply src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java:201]: I wanted to check that it will be skipped in case that it is not prefixed (so it will not fail in this case). But I can remove it from there if it doesn't make sense.

Comment (scholzj) [reply src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java:201]: Why do we want to skip it and not throw an error?

PS: You should also update the PR description.

Comment (im-konge) [reply src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java:201]: Yeah good point. I thought that we can simply ignore it. I will throw an exception then. Thanks :) 

(and update the PR description)

Comment (im-konge) [reply src/test/java/io/strimzi/kafka/quotas/StaticQuotaCallbackTest.java]: Updated

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]
LGTM.

File: README.md [hunk 7]
```diff
@@ -46,23 +46,23 @@ client.quota.callback.static.storage.per.volume.limit.min.available.bytes=536870
...
+| client.quota.callback.static.fetch                                        | Double  | 1.7976931348623157e+308 | Consume bandwidth rate quota (in bytes)                                                                                                                                                                     |
+| client.quota.callback.static.request                                      | Double  | 1.7976931348623157e+308 | Request processing time quota (in seconds)                                                                                                                                                                  |
+| client.quota.callback.static.excluded.principal.name.list                 | String  | ""                      | Semicolon-separated list of principals excluded from the quota. Each principal have to be prefixed with `User:` prefix to exclude it from the quota.                                                        |
```
Comment (k-wall) [inline README.md:59]:
```suggestion
| client.quota.callback.static.excluded.principal.name.list                 | String  | ""                      | Semicolon-separated list of principals excluded from the quota. Each principal has to be prefixed with `User:`.                                                        |
```
have -> has
"to exclude it from the quota" is repetitious and slightly confusing.

**Review by k-wall — APPROVED** [review]
implementation looks okay, one nit in the readme

File: README.md (hunk 7 above)
Comment (im-konge) [reply README.md:59]: Ah yes, thanks 😄

**Review by k-wall — APPROVED** [review]
lgtm (non-binding)

**Review by robobario — APPROVED** [review]
LGTM
